Quantum-Accelerators/quacc

quacc/util/calc.py

ASE.IdealGasThermo.get_entropy() requires pressure in Pa; 1 bar = 1e5 Pa

Units for pressure in entropy calculation

---

.github/workflows/tests.yaml
tests/recipes/dftb/test_dftb_recipes.py

Addresses #105. It looks like a version update to DFTB+ modified the xTB Hamiltonian so the energies are no longer the same.

Re-enable dftbplus unit tests

---

quacc/util/calc.py
quacc/util/db.py
tests/util/test_db.py

Closes #392. It's not possible to do this. See https://github.com/materialsproject/maggma/issues/796

Remove unused `covalent_to_monty` DB scheme

---

docs/src/install/codes.md
quacc/recipes/gaussian/core.py
quacc/recipes/gulp/core.py
quacc/recipes/orca/core.py
quacc/recipes/psi4/core.py
tests/recipes/gaussian/test_gaussian_recipes.py
tests/recipes/orca/test_orca_recipes.py
tests/recipes/psi4/test_psi4_recipes.py
tests/util/test_atoms.py

Closes #421, where in the charge and spin multiplicity flags in the output schema were always set to the default values.
The solution is simple. In the `additional_fields` parameter in the `summarize_run` function, just pass the charge and spin multiplicity so it overrides the default values from the `Molecule` metadata.
For instance, 
```
additional_fields={
"name": "Gaussian Relax",
"charge": charge,
"spin_multiplicity": mult,
},
```
No need to over-engineer here.

Better storing of charge/mult in `Atoms` schema

---

quacc/recipes/gaussian/core.py
quacc/recipes/orca/core.py
quacc/recipes/psi4/core.py
quacc/schemas/ase.py
quacc/schemas/atoms.py
setup.py
tests/recipes/gaussian/test_gaussian_recipes.py
tests/recipes/orca/test_orca_recipes.py

No more playing with `additional_fields`. This time, we are going straight to the source!
The new approach is as follows:
- Each `summarize_run()` style of function now takes a kwarg `charge_and_multiplicity` that is a `Tuple[int, int]` of the charge and spin multiplicity. Pass it to the summarizer, and everything will be taken care of for you downstream. Only has an effect for molecules because `Molecule` objects, not `Structure` objects, have a `charge` and `spin_multiplicity` property.
Note that the `setup.py` file has been updated, so please uninstall pymatgen and `pip install -e .` again. I'm waiting for my PR to be merged, which should be done next week I imagine. Then we can switch to a published release.

Fix Molecule schemas... again!

---

quacc/recipes/lj/core.py
quacc/recipes/tblite/core.py
quacc/schemas/ase.py
tests/recipes/lj/test_lj_recipes.py
tests/recipes/tblite/test_tblite_recipes.py
tests/schemas/test_ase.py

There are two main changes:
- This PR splits up the `"parameters"` key in the output schemas into `"parameters"` (for calculator parameters) and `"opt_parameters"`/`"thermo_parameters"`/`"vib_parameters"` for module-specific parameters.
- This PR adds an LJ frequency job.

Better indexing of parameters in output schemas

---

quacc/schemas/atoms.py
tests/schemas/test_atoms.py

Ensure `atoms_to_metadata` does not crash if dummy atoms are present

---

quacc/calculators/vasp.py
quacc/recipes/emt/parsl/slabs.py
tests/calculators/vasp/test_vasp.py

Source: https://www.vasp.at/wiki/index.php/LELF.
Also closes #524.

Set `NPAR=1` for `LELF = .TRUE.` in `Vasp` calculator; fix Parsl on HPC

---

docs/install/codes.md
src/quacc/recipes/orca/core.py
src/quacc/settings.py
tests/recipes/orca/test_orca_recipes.py

Update ORCA instructions

---

src/quacc/recipes/dftb/core.py
src/quacc/recipes/emt/core.py
src/quacc/recipes/gaussian/core.py
src/quacc/recipes/gulp/core.py
src/quacc/recipes/lj/core.py
src/quacc/recipes/newtonnet/core.py
src/quacc/recipes/orca/core.py
src/quacc/recipes/psi4/core.py
src/quacc/recipes/tblite/core.py
src/quacc/recipes/vasp/core.py
src/quacc/recipes/vasp/mp.py
src/quacc/recipes/vasp/qmof.py
src/quacc/recipes/vasp/slabs.py
src/quacc/util/dicts.py
src/quacc/util/wflows.py
tests/util/test_dicts.py

Closes #733. Tagging @kumaranu.
Now, when you pass a list of swaps to any recipe, it will only replace the designated items even if it's in a nested dictionary.
For instance:
```python
defaults = {"a": 1, "b": {"a": 1, "b": 2}}
calc_swaps = {"c": 3, "b": {"b": 3}}
```
would resolve to
```python
{"a": 1, "b": {"a": 1, "b": 3}, "c": 3}
```

Better handling of dict merging for swaps

---

docs/dev/contributing.md
pyproject.toml
src/quacc/__init__.py

@OmAximani0: Thanks for your report. I agree that the instructions were not clear for developers.
I have made the following changes:
- I have updated the contributor guide to include a step for installing the development version of ASE, just like in the regular installation instructions.
- I have added a check to the `__init__.py` of quacc that checks your ASE version and raises a warning if your version is incompatible.

Better handling of ASE dependency

---

src/quacc/calculators/qchem.py
src/quacc/calculators/vasp.py
src/quacc/utils/calc.py
src/quacc/utils/files.py

Remove redundant `Path()` calls when using `.resolve()`

---

src/quacc/recipes/lj/core.py
src/quacc/recipes/newtonnet/core.py
src/quacc/recipes/newtonnet/ts.py
src/quacc/recipes/tblite/core.py
tests/recipes/newtonnet/test_newtonnet_recipes.py

Clean up NewtonNet recipes some more

---

.github/workflows/tests.yaml
src/quacc/settings.py
src/quacc/utils/calc.py
tests/settings/test_settings.py

Fixes:
- Allows for proper setting of `~/`-based paths for `RESULTS_DIR` and `SCRATCH_DIR`
- Doesn't create a redundant symlink file when `RESULTS_DIR == SCRATCH_DIR`.

Allow for `~`-based paths in `RESULTS_DIR` and `SCRATCH_DIR`, and don't make a symlink if not necessary

---

src/quacc/recipes/dftb/core.py
src/quacc/recipes/emt/core.py
src/quacc/recipes/gaussian/core.py
src/quacc/recipes/gulp/core.py
src/quacc/recipes/lj/core.py
src/quacc/recipes/newtonnet/core.py
src/quacc/recipes/newtonnet/ts.py
src/quacc/recipes/orca/core.py
src/quacc/recipes/psi4/core.py
src/quacc/recipes/tblite/core.py
src/quacc/recipes/vasp/core.py
src/quacc/recipes/vasp/mp.py
src/quacc/recipes/vasp/slabs.py

In principle, the idea was nice in that it would enable editors to show the default params by default. In practice, it's messy because things can accidentally become out of sync between the docstring and the code, and sometimes it's not practical to list all parameters in the docstring itself.

Remove calculator params from docstrings

---

CHANGELOG.md
docs/user/basics/wflow_syntax.md
docs/user/wflow_engine/executors1.md

Fix markdown typos

---

src/quacc/schemas/atoms.py
tests/local/recipes/tblite_recipes/test_tblite_recipes.py

Closes #1344.
If the `charge_and_multiplicity` kwarg is not supplied by a recipe, the best guess will be made for the charge and spin multiplicity so the resulting molecule is valid in the output schema.

Safer handling of spin and charge for molecule

---

src/quacc/calculators/espresso/presets/basic.yaml
src/quacc/recipes/espresso/core.py
src/quacc/recipes/espresso/phonons.py
tests/core/recipes/espresso_recipes/test_espresso.py

Closes #1412. Also, I removed default parameters like `ecutwfc` and `ecutrho`, which should not be in the recipe defaults since they would be the same defaults for every recipe. The recipe defaults should have the minimal info needed to run a reliable calculation for that calculation type; we can put a default preset ("minimal.yaml") that will automatically set `ecutwfc` and `ecutrho` to the max value based on the pseudopotential YAML instead.

Implement a minimal preset for Espresso

---

src/quacc/calculators/espresso/__init__.py
src/quacc/calculators/espresso/espresso.py
src/quacc/calculators/espresso/presets/molecule_efficiency.yaml
src/quacc/calculators/espresso/presets/tough_metal_clusters_efficiency.yaml

1. Allow `Espresso` to be imported as `from quacc.calculators.espresso import Espresso`
2. Remove support for `kpts="gamma"` since the user can just be using the ASE-supported `kpts=None`. In a YAML, `None` is represented as `null` so it's fine there too. There used to be some awkwardness in quacc about dict merging and `None`s, but that's a thing of the past.

More Espresso cleanup

---

docs/user/basics/wflow_decorators.md
src/quacc/wflow_tools/decorators.py
tests/dask/test_dask_syntax.py

Remove `.compute()` in Dask subflow

---

docs/user/wflow_engine/wflow_engines1.md
docs/user/wflow_engine/wflow_engines2.md
pyproject.toml
tests/dask/test_dask_recipes.py
tests/dask/test_dask_syntax.py
tests/dask/test_dask_tutorials.py

Dask documentation cleanup as a result of the new `@subflow` method.

Clean up Dask documentation

---

src/quacc/utils/files.py

When checking to see if a file exists to be copied, use monty's `zpath()` utility to return the zipped extension if present.

Do a `zpath` check on copying files

---

src/quacc/recipes/onetep/_base.py

Similarly, parallel_info needs to be sent in OnetepProfile, also for now the ONETEP_PARALLEL_CMD will not work
We need parallel_info, do you want to change it here, or should I do it in a separate branch?

Changing Path object to str for ONETEP_CMD in base functions

---

src/quacc/calculators/espresso/espresso.py
src/quacc/recipes/espresso/core.py

Currently ase_relax_job will ask QE to compute the wavefunctions/charge-density from scratch at each step, this is highly inefficient.
If a template called Profile.run more than once and the autorestart is activated (default False, but True when calling ase_relax_job) then we turn off QE restart keyword.

Espresso: autorestarting in trivial cases

---

src/quacc/atoms/phonons.py
src/quacc/recipes/common/phonons.py
src/quacc/recipes/emt/phonons.py
src/quacc/recipes/mlp/phonons.py
src/quacc/recipes/tblite/phonons.py
tests/core/atoms/test_phonons.py
tests/core/recipes/emt_recipes/test_emt_phonons.py
tests/core/recipes/mlp_recipes/test_phonon_recipes.py
tests/core/recipes/tblite_recipes/test_tblite_phonons.py

Partially addresses #1652. Still more to do.
1. Use `min_lengths: float | tuple[float, float, float] | None` instead of `min_length: float | None` for phonon keyword argument
2. Change default to 20.0 A

Use `min_lengths` for phonons

---

tests/core/recipes/mlp_recipes/test_core_recipes.py
tests/requirements-mlp.txt

Sanity check inspired by #1652.

Add a test for a MACE-MP-0 relaxation job with `dispersion=True`

---

CHANGELOG.md
docs/user/db/basics.md
src/quacc/schemas/ase.py
src/quacc/schemas/cclib.py
src/quacc/schemas/phonons.py
src/quacc/schemas/vasp.py
src/quacc/settings.py
tests/core/.quacc.yaml
tests/core/recipes/lj_recipes/test_lj_recipes.py
tests/core/settings/test_settings.py

This PR does two things:
1. FIX: It fixes support for `MontyStore`
2. CHANGE: It modifies how Maggma `Store`s are specified in the quacc settings. Now, instead of using `PRIMARY_STORE` with an unwieldy JSON string, a dictionary is provided: `STORE`. It specifies the maggma `Store` type and all arguments to pass to it.
Example:
```yaml title="~/.quacc.yaml"
STORE:
MongoStore: # any store in `maggma.stores.__init__.py` is valid
database: my_db_name
collection_name: my_collection_name
username: my_username
password: my_password
host: localhost
port: 27017
```
- …

Better support for various Maggma stores

---

CHANGELOG.md
docs/user/settings/settings.md
src/quacc/_cli/quacc.py
src/quacc/settings.py
tests/core/.quacc.yaml
tests/core/calculators/vasp/test_vasp.py
tests/core/cli/test_cli.py
tests/core/recipes/gulp_recipes/test_gulp_recipes.py
tests/core/settings/test_settings.py

Closes #1688. Providing a string of "none" or "null" (case-insensitive) will automatically transform to `None`, whether via the CLI, YAML, or environment variables. Same for "true" or "false" (case-insensitive) to `True` or `False`. This is all done at model validation time so we handle all the various settings management cases in one spot.

More robust handling of complex settings types

---

src/quacc/calculators/espresso/espresso.py
src/quacc/recipes/dftb/_base.py
tests/core/atoms/test_atoms_core.py
tests/core/atoms/test_slabs.py
tests/core/calculators/espresso/test_espresso.py
tests/core/calculators/qchem/test_qchem.py
tests/core/calculators/vasp/test_vasp.py
tests/core/calculators/vasp/test_vasp_custodian.py
tests/core/recipes/dftb_recipes/test_dftb_recipes.py
tests/core/recipes/espresso_recipes/test_core.py
tests/core/schemas/test_ase.py

Closes #1700.
Partially addresses #1708.

Stricter matches on raised errors in test suite

---

src/quacc/runners/ase.py
tests/core/recipes/orca_recipes/test_orca_recipes.py
tests/core/utils/test_files.py

Closes #1710.
Allows for the storage of intermediate log files during an ASE optimization.
```python
from quacc.recipes.orca.core import ase_relax_job
from ase.build import molecule
atoms = molecule("H2O")
ase_relax_job(atoms, nprocs=1, opt_params={"store_intermediate_files": True})
```
This would store the intermediate results in a folder step0, step1, step2, etc.

Add an option to store intermediate log files during ASE opt

---

pyproject.toml
src/quacc/settings.py
tests/core/cli/test_cli.py
tests/core/settings/test_settings.py

Closes https://github.com/Quantum-Accelerators/quacc/issues/1702.

Add more pydantic-settings tests

---

src/quacc/runners/prep.py
src/quacc/settings.py
tests/core/recipes/lj_recipes/test_lj_recipes.py
tests/core/recipes/mlp_recipes/test_core_recipes.py
tests/parsl/test_emt_recipes.py

This PR adds a new quacc setting, `CHDIR`, that will allow the user to specify whether any `os.chdir` calls are made, thereby allowing for multiple jobs to be run on a single Python process.
Closes #1641.

Allow for thread-safe execution

---

CHANGELOG.md
docs/user/recipes/recipes_list.md
src/quacc/recipes/vasp/core.py
src/quacc/recipes/vasp/mp.py
src/quacc/schemas/_aliases/vasp.py
tests/core/recipes/vasp_recipes/mocked/test_vasp_recipes.py

This PR addresses https://github.com/Quantum-Accelerators/quacc/discussions/1777 by having each VASP relaxation in a double-relax to be its own job. 

Modify VASP double relaxes to be a flow

---

tests/core/recipes/espresso_recipes/conftest.py
tests/core/recipes/espresso_recipes/test_bands.py
tests/core/recipes/espresso_recipes/test_core.py
tests/core/recipes/espresso_recipes/test_dos.py
tests/core/recipes/espresso_recipes/test_phonons.py
tests/dask/test_emt_recipes.py
tests/dask/test_espresso_recipes.py

As discussed in https://github.com/Quantum-Accelerators/quacc/pull/1789 some parallelization flags can help make espresso tests faster
Closes #1818.

Espresso: faster tests

---

src/quacc/calculators/espresso/espresso.py
tests/core/calculators/espresso/test_espresso.py

Fix for https://github.com/Quantum-Accelerators/quacc/issues/1807
Please do not hesitate to ping me on this kind of issues

Make ESPRESSO compatible with chdir: False

---

src/quacc/settings.py
tests/core/settings/test_settings.py

Raise a `ValueError` if `RESULTS_DIR` or `SCRATCH_DIR` is relative.
Closes #1858.

Raise a ValueError if RESULTS_DIR or SCRATCH_DIR is relative

---

src/quacc/recipes/vasp/slabs.py

Here, I have changed the default NEDOS from 5001 to 3001 in the VASP static jobs. The value of 3001 represents a 10x increase from the default, which seems logical. A dedicated NSCF job will be made with #1840 anyway, which will be more robust in terms of DOS.

Change NEDOS from 5001 to 3001 in VASP `static_job`

---

src/quacc/settings.py

Set `CHDIR` setting to `False`, finally supporting multiple calculations per Python process.

Set `CHDIR` to `False`

---

src/quacc/recipes/onetep/_base.py
src/quacc/recipes/onetep/core.py
src/quacc/recipes/vasp/_base.py
src/quacc/recipes/vasp/core.py
src/quacc/schemas/_aliases/vasp.py
tests/core/recipes/vasp_recipes/mocked/test_vasp_recipes.py

Add an `ase_relax_job` for VASP

---

src/quacc/recipes/dftb/_base.py
src/quacc/recipes/dftb/core.py
src/quacc/recipes/espresso/_base.py
src/quacc/recipes/espresso/bands.py
src/quacc/recipes/espresso/core.py
src/quacc/recipes/espresso/dos.py
src/quacc/recipes/espresso/phonons.py
src/quacc/recipes/gaussian/_base.py
src/quacc/recipes/gaussian/core.py
src/quacc/recipes/gulp/_base.py
src/quacc/recipes/gulp/core.py
src/quacc/recipes/onetep/_base.py
src/quacc/recipes/onetep/core.py
src/quacc/recipes/orca/_base.py
src/quacc/recipes/orca/core.py
src/quacc/recipes/psi4/_base.py
src/quacc/recipes/psi4/core.py
src/quacc/recipes/qchem/_base.py
src/quacc/recipes/qchem/core.py
src/quacc/recipes/qchem/ts.py
src/quacc/recipes/vasp/_base.py
src/quacc/recipes/vasp/core.py
src/quacc/recipes/vasp/mp.py
src/quacc/recipes/vasp/qmof.py
src/quacc/recipes/vasp/slabs.py

Renamed `base_fn` and `base_opt_fn` to `run` and `run_ase_opt`, respectively.

Rename `_base` functions to be interpretable

---

src/quacc/recipes/dftb/_base.py
src/quacc/recipes/dftb/core.py
src/quacc/recipes/espresso/_base.py
src/quacc/recipes/espresso/bands.py
src/quacc/recipes/espresso/core.py
src/quacc/recipes/espresso/dos.py
src/quacc/recipes/espresso/phonons.py
src/quacc/recipes/gaussian/_base.py
src/quacc/recipes/gaussian/core.py
src/quacc/recipes/gulp/_base.py
src/quacc/recipes/gulp/core.py
src/quacc/recipes/onetep/_base.py
src/quacc/recipes/onetep/core.py
src/quacc/recipes/orca/_base.py
src/quacc/recipes/orca/core.py
src/quacc/recipes/psi4/_base.py
src/quacc/recipes/psi4/core.py
src/quacc/recipes/qchem/_base.py
src/quacc/recipes/qchem/core.py
src/quacc/recipes/qchem/ts.py
src/quacc/recipes/vasp/_base.py
src/quacc/recipes/vasp/core.py
src/quacc/recipes/vasp/mp.py
src/quacc/recipes/vasp/qmof.py
src/quacc/recipes/vasp/slabs.py

Rename `base_fn` and `base_opt_fn` to `run_and_summarize` and `run_and_summarize_opt`

Rename `_base` functions

---

CHANGELOG.md
src/quacc/recipes/onetep/_base.py
src/quacc/recipes/orca/core.py
src/quacc/settings.py
tests/core/recipes/orca_recipes/test_orca_recipes.py

1. Remove `slowconv` from ORCA recipe defaults
2. Make the various executable commands `str` type instead of `Path` type since apparently (?) there is the possibility for a weird permission error if it's a `Path`. Not quite sure how, but alas...

Remove `slowconv` from defaults and make executable commands `str` type

---

src/quacc/recipes/espresso/phonons.py
tests/dask/test_espresso_recipes.py

It seems that the "job within a job" concept is not well appreciated by Parsl when using custom executors (redecorated jobs). Leading to problems as mentioned in #1852
Changing this `job` (_ph_recover_job) to a `subflow` and removing strip_decorators does make things work. We have now to understand how this can possibly affect other workflow engines.

Issues with the grid_phonon_flow and custom decorators when using Parsl

---

src/quacc/schemas/_aliases/atoms.py
src/quacc/schemas/ase.py
src/quacc/schemas/atoms.py
tests/core/schemas/test_ase.py
tests/core/schemas/test_cclib_schema.py
tests/core/schemas/test_vasp_schema.py

Remove the redundant `atoms_info` key in the output schemas, since this is already captured by MSONable `Atoms`.

Remove redundant `atoms_info` in output schema

---

src/quacc/runners/ase.py

Apparently, a while back ASE changed from pickle to JSON for the optimizer trajectory, so we've been dumping to a pickle file extension even though it's JSON format. I fixed the file extension now.

The optimizer trajectory now has the proper JSON extension, not pickle

---

src/quacc/recipes/gulp/_base.py
src/quacc/recipes/onetep/_base.py
src/quacc/recipes/orca/_base.py
src/quacc/recipes/psi4/core.py

This PR increases the "hackability" of recipes for users that are doing funky things with a custom calculator. Namely, some recipes don't take a `**calc_kwargs` because, well, there is no need to. An example of this is the ORCA recipes since the ASE `ORCA` calculator takes `orcasimpleinput` and `orcablocks` as dedicated keyword arguments; there is no need for the user to pass an arbitrary set of `**calc_kwargs` because the possible options are clearly enumerated in ASE. However, if someone makes a custom `ORCA` calculator where they add on additional keyword arguments, then they can't get passed anywhere. This is likely a rare edge case, but it's pretty painless to implement.

Increase hackability of recipes

---

src/quacc/schemas/ase.py
tests/core/schemas/test_ase.py

Clean up schemas

---

src/quacc/recipes/espresso/_base.py

No need for us to hide methods that are already hidden.

Remove double `_` methods

---

src/quacc/utils/dicts.py
tests/core/utils/test_dicts.py

Add a sanity check before writing out results

---

src/quacc/calculators/espresso/espresso.py

Clean up `Path.open` lines

---

src/quacc/recipes/mlp/_base.py
src/quacc/recipes/mlp/core.py
src/quacc/recipes/mlp/phonons.py
tests/core/recipes/mlp_recipes/test_core_recipes.py

Closes #1972 by adding support for 'mace-mp-0' and adding a deprecated warning for 'mace' in the mlp recipe. 
Adding 'mace-mp-0':
- Added as a Literal in the arguments for static_job() and relax_job() in core.py, phonon_flow() in phonons.py, and pick_calculator() in _base.py
- Added an elif conditional for 'mace-mp-0' in pick_calculator() in _base.py 
- Added 'mace-mp-0 as a Literal for tests in test_core_recipes.py in mlp_recipes test folder.
Deprecating 'mace':
- Added 'import deprecated from monty.dev' in _base.py
- Updated pick_calculator() docstring with deprecation warning according to NumPy docstring standard in _base.py
- Added mace_warning() with 'deprecated' decorator invoked in pick_calculator() in _base.py
Additional:
- Changed 'from ase.calculator.calculator' to 'from …

Deprecate "mace" mlp recipes (replaced with "mace-mp-0")

---

docs/install/codes.md
src/quacc/calculators/vasp/vasp.py
tests/core/calculators/vasp/test_vasp.py

In VASP 6.4.3+, the vdw_kernel.bindat file is not needed for vdW runs. The warning is removed.

No longer raise a warning if vdw_kernel.bindat is missing

---

src/quacc/wflow_tools/decorators.py
tests/parsl/test_syntax.py

Closes https://github.com/Quantum-Accelerators/quacc/issues/1886.
Adding `@wraps` does not work, special keywords are not passed to Parsl correctly in this case (I don't know why).
To perform proper testing, an `HighThroughputExecutor` will have to be loaded in the test.

Support special Parsl keywords

---

src/quacc/recipes/common/phonons.py
src/quacc/recipes/emt/phonons.py
src/quacc/recipes/mlp/phonons.py
src/quacc/recipes/tblite/phonons.py

This PR removes the redundant call to `get_phonopy()` in `quacc.recipes.common.phonons`. It also fixes a bug (?) where the `Phonopy` object was constructed based on the _unrelaxed_ structure rather than the relaxed structure.

Remove redundant call to `get_phonopy` and fix bug in common phonon subflow

---

src/quacc/recipes/vasp/qmof.py
tests/core/recipes/vasp_recipes/mocked/test_vasp_recipes.py

Closes #2117. Fixed passing of the WAVECAR between steps in the QMOF recipe.
There are also a few other minor changes: 1) I removed the `preset` keyword argument because it is not QMOF compatible if "QMOFSet" is not used. 2) I did some cleanup of the internal (`_` prepended) functions for increased robustness. 3) I force `VASP_USE_CUSTODIAN` to be `True` because otherwise WAVECAR issues can occur when going from gamma-point only to standard VASP versions.
@honghuikim: Thank you again for the report. This PR should hopefully fix it. Unfortunately, I do not have very thorough tests set up for WAVECAR passing yet, so please don't hesitate to let me know if the problem persists after this is merged. Thank you!
- If you are …

Fix copying of WAVECAR in QMOF recipes

---

src/quacc/settings.py

Previously, `quacc` would try to auto-detect which workflow engine you had installed and then set that as the default. This, however, is too smart for its own good. It often leads to user confusion because if you install (say) atomate2 and get jobflow installed as a side-effect, it will auto-change to jobflow without the user knowing. This behavior has been disabled. As noted in the docs, the user should specific explicitly which workflow engine to use.
- When your code is ready for review, ping one of the [active …

Breaking: Don't try to auto-detect the workflow engine

---

src/quacc/settings.py

This PR changes `VASP_MAG_CUTOFF` from 0.05 to 0.02 to more closely match the protocol used by MP.

Change `VASP_MAG_CUTOFF` from 0.05 to 0.02

---

docs/user/settings/settings.md
src/quacc/__init__.py
src/quacc/recipes/newtonnet/ts.py
src/quacc/recipes/qchem/ts.py
src/quacc/recipes/vasp/qmof.py
src/quacc/settings.py
tests/core/calculators/vasp/test_vasp.py
tests/core/recipes/espresso_recipes/test_phonons.py
tests/core/recipes/gulp_recipes/test_gulp_recipes.py
tests/core/recipes/lj_recipes/test_lj_recipes.py
tests/core/recipes/tblite_recipes/test_tblite_recipes.py
tests/core/recipes/vasp_recipes/mocked/test_vasp_recipes.py
tests/core/runners/test_ase.py
tests/core/runners/test_prep.py
tests/core/settings/test_settings.py
tests/parsl/test_emt_recipes.py
tests/prefect/test_syntax.py

Adds the ability to change settings temporarily via a context handler.
Closes #2119.

Add support for setting changes with a context handler

---

tests/core/recipes/mlp_recipes/test_core_recipes.py
tests/core/recipes/mlp_recipes/test_phonon_recipes.py
tests/requirements-mlp.txt

Closes #2090.
Waiting on:
- matgl 1.1.2 (see https://github.com/materialsvirtuallab/matgl/pull/259)

Fix the MLP tests

---

docs/user/settings/file_management.md
src/quacc/runners/ase.py
src/quacc/runners/prep.py
tests/core/recipes/dftb_recipes/test_dftb_recipes.py
tests/core/runners/test_prep.py
tests/core/settings/test_settings.py

Closes #2016 by storing failed calculations in a renamed `failed-quacc-...` directory. The only user-facing change here is the `tmp-quacc-12345` becomes `failed-quacc-12345` upon failure.

Store failed calculations with a dedicated naming scheme

---

CHANGELOG.md
src/quacc/schemas/_aliases/ase.py
src/quacc/schemas/ase.py
tests/core/recipes/orca_recipes/test_orca_recipes.py
tests/core/recipes/vasp_recipes/mocked/test_vasp_recipes.py
tests/core/schemas/test_ase.py
tests/covalent/test_emt_recipes.py
tests/dask/test_emt_recipes.py
tests/parsl/test_emt_recipes.py
tests/prefect/test_emt_recipes.py
tests/redun/test_emt_recipes.py

Put `fmax` in `parameters_opt` within the schema instead of the base level. Closes #1970.

Update fmax in schema

---

src/quacc/settings.py
tests/core/settings/test_settings.py

As the title states. There is no need for absolute paths anymore if we don't have `chdir` calls.

Remove restriction on absolute paths for RESULTS and SCRATCH directories

---

src/quacc/schemas/_aliases/ase.py
src/quacc/schemas/ase.py

This mainly updates a schema to reflect changes in https://gitlab.com/ase/ase/-/merge_requests/3360. The only user-facing change is that `nsteps` is moved slightly.

Update `Optimizer.todict()` call in ASE opt schema

---

src/quacc/recipes/mlp/core.py
src/quacc/runners/ase.py

Small change to `run_calc` so that arbitrary properties can be requested (including but not limited to energy/forces), and small change to the mlp.core.static_job so that forces are not already required for those calculators. This is also useful for ML models that predict properties beyond energy/forces. 
Currently, if a MLP calculator does not implement forces, mlp.core.static_job will throw a PropertyNotImplemented error.

Support in run_calcs for models that implement arbitrary properties, and support for MLPs that don't have forces

---

src/quacc/atoms/deformation.py

The default [value](https://github.com/materialsproject/pymatgen/blob/163cc01e0251525f5ab8f48776511411754012a9/pymatgen/analysis/elasticity/strain.py#L110) from pymatgen is `0.06`.

Fix a small typo in elastic

---

docs/user/recipes/recipes_intro.md

Closes #2267.
This PR seeks to further clarify what `**calc_kwargs` means in the function signature, providing more detailed guidance for users in the introductory documentation. This is based on @wladerer's initial point of confusion in https://github.com/Quantum-Accelerators/quacc/discussions/2265.

Clarify usage of `**calc_kwargs` in docs

---

src/quacc/recipes/mlp/_base.py

This PR removes an old deprecated keyword argument `mace` in the MLP recipes. The keyword argument in the docstring is `mace-mp-0`.

Remove deprecated `mace` method

---

src/quacc/wflow_tools/job_patterns.py
tests/core/wflow/test_job_patterns.py
tests/prefect/test_map_partitions.py

This draft PR adds job patterns that are common in high-throughput workflows. When running many jobs on the same flow (say `result = map(my_job, range(1000))`) , many workflow managers will get sad (network/db/load issues) with too many jobs. This PR is inspired by the dask bag partitions and map operator. 
For example:
```
@job
def testjob(**kwargs):
print(kwargs)
@flow
def testflow():
num_partitions = 2
result = map_partitioned_lists(
testjob,
num_partitions=num_partitions,
test_arg_1=partition([1,2,3,4,5], num_partitions),
test_arg_2=partition(["a", "b", "c","d","e"], num_partitions),
)
testflow()
```
should yield:
```
{'test_arg_1': 1, 'test_arg_2': 'a'}
{'test_arg_1': 2, 'test_arg_2': 'b'}
{'test_arg_1': 3, 'test_arg_2': 'c'}
{'test_arg_1': 4, 'test_arg_2': 'd'}
{'test_arg_1': 5, …
```

job patterns for partitioning lists and mapping onto them

---

src/quacc/recipes/vasp/core.py

As noted in https://github.com/Quantum-Accelerators/quacc/issues/1887, the VASP recipes are the only ones throughout quacc with `relax_cell = True` by default (namely: `relax_job` and `ase_relax_job`). This can lead to unexpected behavior for users that run multiple codes in quacc. To streamline things, eventually we will make `relax_cell = False` by default. This would be a notable breaking change, so we will not do so for some time. The warning may be perceived as annoying, but it is perhaps worthwhile.
- Your PR should be focused on a [single feature addition or bugfix](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/best-practices-for-pull-requests#write-small-prs).
- Your PR should have relevant, comprehensive [unit …

Warn users about a future breaking change to `relax_cell` in VASP recipes

---

src/quacc/atoms/slabs.py
src/quacc/calculators/espresso/espresso.py
src/quacc/calculators/vasp/vasp.py
src/quacc/calculators/vasp/vasp_custodian.py
src/quacc/recipes/gulp/_base.py
src/quacc/recipes/vasp/core.py
src/quacc/runners/prep.py
src/quacc/schemas/_aliases/cclib.py
src/quacc/schemas/vasp.py
src/quacc/utils/files.py
src/quacc/utils/lists.py
src/quacc/wflow_tools/job_patterns.py

This merge request addresses some of the type hinting issues identified by MyPy.
Ref: https://github.com/Quantum-Accelerators/quacc/issues/782.

Address some mypy type hinting issues

---

src/quacc/recipes/espresso/_base.py
src/quacc/recipes/espresso/core.py
src/quacc/recipes/espresso/dos.py
src/quacc/recipes/espresso/phonons.py
src/quacc/types.py

Address MyPy type-checking errors in the espresso recipes module.
Ref: https://github.com/Quantum-Accelerators/quacc/issues/782.

fix mypy issues for espresso recipes

---

src/quacc/__init__.py
src/quacc/atoms/core.py
src/quacc/atoms/phonons.py
src/quacc/calculators/espresso/espresso.py
src/quacc/calculators/espresso/utils.py
src/quacc/calculators/qchem/io.py
src/quacc/calculators/qchem/params.py
src/quacc/calculators/vasp/vasp.py
src/quacc/calculators/vasp/vasp_custodian.py
src/quacc/runners/ase.py
src/quacc/schemas/ase.py
src/quacc/schemas/atoms.py
src/quacc/schemas/cclib.py
src/quacc/schemas/vasp.py
src/quacc/types.py
src/quacc/utils/dicts.py
src/quacc/utils/kpts.py
src/quacc/wflow_tools/customizers.py
src/quacc/wflow_tools/decorators.py

Fixed mypy issues in the calculators and schema modules.
FYI: @Andrew-S-Rosen, we reduced the number of mypy errors from 320 to 160. There are still over 130 errors in `types.py`, which I will try to fix in another PR.
- The `Atoms` used in Quacc for the moment overload the `ASE Atoms` class with attributes and functions like `charges`, `as_dict()`, and `from_dict()`, which mypy does not accept. Should we ignore these, or create a `QuaccAtom` class with the necessary attributes and functions? what do you think ?
- If you are an external contributor, you will see a comment from [@buildbot-princeton](https://github.com/buildbot-princeton). …

Fix mypy issues in calculators and schema modules

---

src/quacc/calculators/espresso/espresso.py

This pull request fixes a `ValueError` that occurs when checking the `kpts` parameters in `_cleanup_params()` of the Espresso module. Previously, using a numpy array for `kpts` resulted in an ambiguous truth value error. Numpy array input is accepted as a form of manual kpoint specification per [ASE documentation](https://wiki.fysik.dtu.dk/ase/ase/calculators/espresso.html).
@Andrew-S-Rosen please kindly review.
- [N/A] My PR has relevant, comprehensive [unit tests](https://quantum-accelerators.github.io/quacc/dev/contributing.html#unit-tests).
- If you are an external contributor, you will see a comment from …

Fix ValueError when checking kpts in Espresso module

---

src/quacc/recipes/dftb/core.py
src/quacc/recipes/emt/core.py
src/quacc/recipes/emt/md.py
src/quacc/recipes/espresso/bands.py
src/quacc/recipes/espresso/core.py
src/quacc/recipes/espresso/dos.py
src/quacc/recipes/espresso/phonons.py
src/quacc/recipes/gaussian/core.py
src/quacc/recipes/gulp/core.py
src/quacc/recipes/lj/core.py
src/quacc/recipes/mlp/core.py
src/quacc/recipes/newtonnet/core.py
src/quacc/recipes/newtonnet/ts.py
src/quacc/recipes/onetep/core.py
src/quacc/recipes/orca/core.py
src/quacc/recipes/psi4/core.py
src/quacc/recipes/qchem/core.py
src/quacc/recipes/qchem/ts.py
src/quacc/recipes/tblite/core.py
src/quacc/recipes/vasp/core.py
src/quacc/recipes/vasp/qmof.py
src/quacc/recipes/vasp/slabs.py

This PR addresses the request in https://github.com/Quantum-Accelerators/quacc/issues/2399 to have an `additional_fields` keyword argument for all `@job`s in quacc. Will not merge without input from @tomdemeyere.

Add `additional_fields` to all `@job`s

---

src/quacc/calculators/espresso/espresso.py
src/quacc/settings.py

As discussed in (https://github.com/Quantum-Accelerators/quacc/issues/2419) this is an attempt to fix the current issue with the 
Users can redecorate their job, adding the `parsl_resource_specification`, Parsl take these informations and define environment variables such as `PARSL_MPI_PREFIX`. If the users redecorate multiple jobs, different `PARSL_MPI_PREFIX` will be accessible on a per job basis.
``` python
resource_specification_slow = {
"num_nodes": 1,
"ranks_per_node": 128,
"num_ranks": 128,
"launcher_options": "-vv --cpu-freq=2250000 --hint=nomultithread --distribution=block:block",
}
resource_specification_fast = {
"num_nodes": 4,
"ranks_per_node": 128,
"num_ranks": 128 * 4,
"launcher_options": "-vv --cpu-freq=2250000 --hint=nomultithread --distribution=block:block",
} …
```

PARSL_MPI_PREFIX moved to the espresso calculator

---

src/quacc/__init__.py
src/quacc/runners/prep.py
tests/core/recipes/dftb_recipes/test_dftb_recipes.py
tests/core/recipes/espresso_recipes/test_core.py
tests/core/recipes/qchem_recipes/mocked/test_qchem_recipes.py
tests/core/runners/test_ase.py
tests/core/runners/test_prep.py

This PR seeks to close #2407 by raising a custom `JobFailure` exception when a job fails, which can be used to `try`/`except` calculations more easily. The `JobFailure` raises the parent ASE error but also has a `directory` attribute that can be easily accessed by the user without any need to sift through the log file. The directory info was already being logged, but now it's also present in the traceback. There is also a `parent_error` attribute to ensure the original exception is still accessible by the end user.
Pinging @tomdemeyere for review.

Raise a custom `JobFailure` error when a job fails

---

CHANGELOG.md
src/quacc/__init__.py
src/quacc/atoms/core.py
src/quacc/atoms/slabs.py
src/quacc/calculators/espresso/espresso.py
src/quacc/calculators/espresso/utils.py
src/quacc/calculators/qchem/params.py
src/quacc/calculators/vasp/params.py
src/quacc/recipes/gulp/_base.py
src/quacc/recipes/mlp/_base.py
src/quacc/recipes/vasp/qmof.py
src/quacc/runners/ase.py
src/quacc/runners/prep.py
src/quacc/schemas/prep.py
src/quacc/schemas/thermo.py
src/quacc/schemas/vasp.py
src/quacc/settings.py
src/quacc/utils/dicts.py
src/quacc/utils/files.py
tests/core/.quacc.yaml
tests/core/calculators/vasp/test_vasp.py
tests/core/recipes/dftb_recipes/test_dftb_recipes.py
tests/core/recipes/emt_recipes/test_emt_recipes.py
tests/core/recipes/espresso_recipes/test_phonons.py
tests/core/runners/test_ase.py
tests/core/schemas/test_thermo.py
tests/core/schemas/test_vasp_schema.py
tests/core/settings/test_settings.py
tests/core/utils/test_dicts.py
tests/core/utils/test_files.py

Provides a setting to store the log files to disk. Before, it was only shown in the console. Now, we have an option to write it out to a custom file if desired by the user.
@tomdemeyere: I think this explains part of the confusion. I had assumed the logger metadata was being written out to disk and was confused why you had to go digging through folders to find out which failed. However, it was only shown in the console.

Add a setting to store the logger file to disk

---

src/quacc/wflow_tools/job_patterns.py
tests/core/wflow/test_job_patterns.py

Add a helper utility to unpartition partitioned lists.
Add a simple helper utility to unpartition partitioned lists. Example usage:
```
partitioned_lists = partition(my_list, num_partitions)
partitioned_results = map_partitions(myfun, partitioned_lists, ...)
results = unpartition(partitioned_results)
```

add wflow_tools.job_patterns.unpartition

---

docs/user/basics/wflow_syntax.md
docs/user/wflow_engine/executors.md
docs/user/wflow_engine/wflow_engines1.md
docs/user/wflow_engine/wflow_engines2.md
src/quacc/wflow_tools/decorators.py
src/quacc/wflow_tools/prefect_utils.py
tests/prefect/test_customizers.py
tests/prefect/test_emt_recipes.py
tests/prefect/test_map_partitions.py
tests/prefect/test_syntax.py
tests/prefect/test_tutorials.py

Prefect3 now requires all jobs to be resolved before a flow exits. If you return a job that is still running, this causes warnings and problems.
Also, return futures/states is good in that you can avoid passing around data until it's needed, but annoying in that you may ended up with complex structures that have prefect futures embedded inside them. 
This PR introduces a function `resolve_futures_to_results` modeled on the prefect function `resolve_futures_to_states` that will recursively crawl python collections and resolve any futures to their final results. This function is called on any results that are returned by a quacc flow so that they are properly resolved before the flow finishes.
```
import time
from quacc import flow, job
@job
def slow_math():
time.sleep(2)
return 5
@flow() …
```

resolve all quacc/prefect flow futures to data make prefect happy 

---

src/quacc/calculators/vasp/params.py

@Andrew-S-Rosen  I found the problem. It is not `emmet-core` or `pymargen` version issue. `input_set.potcar` needs line splitting similar to what is done at [line 424](https://github.com/chiang-yuan/quacc/blob/ea34aa63b76d7cdd3c1eed0d674827dd04a16337/src/quacc/calculators/vasp/params.py#L424)
I tested the vasp workflow locally and didn't run into any errors
This will close issue #2457 and close https://github.com/materialsproject/atomate2/pull/984

add line split for potcar_symbols

---

src/quacc/calculators/espresso/espresso.py

Since it's relevant to Quantum Espresso, the "INCAR" used for VASP was removed to avoid confusion.
Feel free to reject this pull request because it's just a small fix of the document. 
Since it's relevant to Quantum Espresso, the "INCAR" used for VASP was removed to avoid confusion.

fix doc of espresso.py

---

pyproject.toml
src/quacc/recipes/mlp/_base.py
src/quacc/recipes/mlp/core.py
src/quacc/recipes/mlp/phonons.py
tests/core/recipes/mlp_recipes/test_core_recipes.py
tests/requirements-mlp.txt

Added **sevennet** to the MLP recipes based on issue #2429. 
Key changes include:
1. Added sevennet implementation to mlp recipes
2. Created unit tests to validate sevennet functionality
3. Ensured compatibility with existing MLP workflows
-[X] My PR is focused on a single feature addition [#2429 ].
-[X] My PR has relevant, comprehensive unit tests.
-[X] My PR is on a custom branch (feature/sevennetMLP).

feat: add sevennet support to mlp recipes

---

src/quacc/calculators/vasp/params.py
tests/core/calculators/vasp/test_vasp.py

Fix sorting with MP sets

---

pyproject.toml
tests/requirements-mlp.txt

We have recently yanked an incorrectly versioned orb-models from PyPI and re-uploaded with the correct version. This PR corrects the version of orb-models to avoid install errors. 

Change Orb Version

---

src/quacc/recipes/vasp/core.py
tests/core/recipes/vasp_recipes/mocked/test_vasp_recipes.py

For many months now, the `relax_job` and `ase_relax_job` in `quacc.recipes.vasp.core` had a warning that `relax_cell` would be set to `False` by default in the future to be consistent with other workflows in quacc. This change is now implemented.

Change `relax_cell` to `False` in core VASP workflows per warning

---

.github/workflows/tests.yaml
tests/core/recipes/mlp_recipes/test_core_recipes.py
tests/requirements-mlp1.txt
tests/requirements-phonons.txt

Simplify huggingface downloads

---

src/quacc/calculators/espresso/utils.py
tests/core/recipes/espresso_recipes/test_bands.py

Closes https://github.com/Quantum-Accelerators/quacc/issues/2724
@BCAyers2000

Fix the overlapping filenames when using `bands.x`

---

src/quacc/recipes/common/elastic.py

`relax_cell=False` should be enforced for relaxations of deformed structures in the `_elastic_tensor_subflow`

enforce relax_cell False for correct elastic calculations

---

pyproject.toml
src/quacc/recipes/common/elastic.py
tests/requirements-mlp2.txt
tests/requirements.txt

Emmet 0.86 makes material_id optional and moves it in the function definition, breaking this code. Since we don't really need a material_id anyways, just remove it. This will now only work on emmet>=0.86.0.

Remove material_id from elasticity

---

docs/user/db/basics.md
docs/user/recipes/recipes_intro.md
docs/user/recipes/workflows.md
docs/user/settings/file_management.md
src/quacc/_cli/quacc.py
src/quacc/recipes/dftb/_base.py
src/quacc/recipes/dftb/core.py
src/quacc/recipes/emt/core.py
src/quacc/recipes/gaussian/core.py
src/quacc/recipes/lj/core.py
src/quacc/recipes/mlp/_base.py
src/quacc/recipes/mlp/core.py
src/quacc/runners/ase.py
src/quacc/schemas/ase.py
src/quacc/schemas/phonons.py
src/quacc/schemas/thermo.py
src/quacc/schemas/vasp.py
src/quacc/settings.py
src/quacc/utils/dicts.py
tests/core/.quacc.yaml
tests/core/recipes/emt_recipes/test_emt_recipes.py
tests/core/recipes/lj_recipes/test_lj_recipes.py
tests/core/schemas/test_ase.py
tests/core/schemas/test_thermo.py
tests/core/schemas/test_vasp_schema.py
tests/core/settings/test_settings.py
tests/core/utils/test_dicts.py

This PR removes two features:
- There is no more `quacc_results.json.gz` file written out to disk. This turned out to be way more trouble than it was worth, over-complicating recipes by requiring the use of schemas with knowledge of the current working directory at all times.
- There is no more `STORE` quacc setting. Storing in databases will require calling the `results_to_db` function or using a workflow engine (e.g. Jobflow, FireWorks, Prefect, Covalent).

Breaking: No longer support `quacc_results.json` file and automated storing of data in the `STORE`

---

src/quacc/calculators/vasp/params.py
src/quacc/calculators/vasp/vasp.py
tests/core/calculators/vasp/test_vasp.py

Improve the `Vasp` calculator's handling of KSPACING, e.g. automatically choosing the gamma-point only version of VASP based on how many kpoints there are and making sure there is no conflict between kpts and KSPACING.

Clean up kspacing handling

---

src/quacc/runners/generic.py
tests/core/runners/test_generic.py

In this PR I attempt to implement a `GenericRunner` which can be used to run external commands, the class currently:
- Manage IO via ClassVar which can be changed when subclassing.
- Take the command and split it, this is final, new instance should be created if the command needs to be changed.
- Users can send custom environments if needed.
Hope that's not out of scope 🙃

A `GenericRunner` to run arbitrary commands

---

src/quacc/calculators/vasp/params.py
src/quacc/calculators/vasp/presets/DefaultSetHybrid.yaml
src/quacc/calculators/vasp/presets/DefaultSetMetaGGA.yaml
tests/core/calculators/vasp/test_vasp.py

When ALGO = "All", we should be using ISEARCH = 1 per the VASP manual.

Use ISEARCH = 1 when ALGO = All in VASP
