- quacc/presets/vasp/MPScanSet.yaml
- quacc/recipes/emt/core.py
- quacc/recipes/emt/jobflow/slabs.py
- quacc/recipes/emt/slabs.py
- quacc/recipes/lj/core.py
- quacc/recipes/vasp/jobflow/slabs.py
- quacc/recipes/vasp/mp.py
- quacc/recipes/vasp/qmof.py
- quacc/recipes/vasp/slabs.py
- tests/recipes/vasp/conftest.py
- tests/recipes/vasp/test_vasp_recipes.py
> Add MP-compatible VASP workflow

- docs/src/user/advanced/jobflow.md
> Add a link to Janine's Jobflow tutorial

- quacc/recipes/vasp/jobflow/slabs.py
- quacc/recipes/vasp/mp.py
- quacc/schemas/ase.py
- tests/schemas/test_ase.py
> Change `input_structure` to `input_atoms` in `Atoms` schema

- .github/workflows/docs.yaml
- CHANGELOG.md
- docs/src/conf.py
- quacc/calculators/vasp.py
- quacc/presets/vasp/BulkSet.yaml
- quacc/settings.py
- quacc/util/atoms.py
- setup.py
- tests/calculators/vasp/test_vasp.py
Closes #374. See https://github.com/materialsproject/atomate2/issues/365
> Add `EFERMI = MIDGAP` for VASP 6.4.0+

- .github/workflows/tests.yaml
- quacc/schemas/ase.py
- quacc/util/calc.py
- tests/recipes/tblite/test_tblite_recipes.py
- tests/util/test_calc.py
The way we've been parsing trajectory data is not compatible with sella.
> Fix sella test

- quacc/schemas/ase.py
- quacc/util/thermo.py
> More accurate schemas for storing the vibrational modes of ideal gases

- .gitignore
- README.md
- docs/src/about/faq.md
- docs/src/install/advanced/index.md
- docs/src/install/advanced/jobflow.md
- docs/src/install/advanced/parsl.md
- docs/src/install/covalent.md
- docs/src/install/install.md
- docs/src/user/advanced/index.md
- docs/src/user/advanced/jobflow.md
- docs/src/user/advanced/parsl.md
- docs/src/user/basics.md
- docs/src/user/covalent.md
- setup.py
> Provide minimal working examples for Parsl

- .gitignore
- docs/src/install/install.md
- docs/src/user/covalent.md
- quacc/settings.py
> Clarify docs

- docs/src/install/codes.md
- docs/src/user/basics.md
- setup.py
> Further clarifications to the getting started tutorial

- .github/workflows/tests.yaml
- docs/install/wflow_engines.md
- docs/user/executors.md
- pyproject.toml
- src/quacc/recipes/vasp/slabs.py
Probably also want to store the relax in slab workflows?
> Clean up test suite

- docs/user/executors.md
- docs/user/wflow_engines.md
- docs/user/wflow_syntax.md
- tests/prefect_tests/test_prefect.py
> Add code annotations

- docs/user/wflow_engines.md
- docs/user/wflow_overview.md
- docs/user/wflow_syntax.md
- src/quacc/recipes/emt/parsl/slabs.py
- src/quacc/recipes/emt/slabs.py
- tests/parsl_tests/test_parsl.py
- tests/prefect_tests/test_prefect.py
> Clarify Parsl docs

- docs/user/atomate2.md
- mkdocs.yml
> Add documentation on how to link quacc to atomate2

- docs/user/file_transfers.md
- mkdocs.yml
- src/quacc/recipes/dftb/core.py
- src/quacc/recipes/emt/core.py
- src/quacc/recipes/gaussian/core.py
- src/quacc/recipes/gulp/core.py
- src/quacc/recipes/lj/core.py
- src/quacc/recipes/orca/core.py
- src/quacc/recipes/psi4/core.py
- src/quacc/recipes/tblite/core.py
- src/quacc/recipes/vasp/core.py
- src/quacc/recipes/vasp/mp.py
- src/quacc/recipes/vasp/qmof.py
- src/quacc/recipes/vasp/slabs.py
> Improve ease of inter-job file transfers

- CHANGELOG.md
- src/quacc/calculators/vasp.py
- tests/calculators/vasp/test_vasp.py
https://www.vasp.at/forum/viewtopic.php?p=23038
> Remove LMAXTAU handler

- docs/install/wflow_engines.md
- docs/start/demo.md
- docs/user/wflow_engines.md
- docs/user/wflow_overview.md
Emphasize Covalent and Parsl as the go-tos.
> Clarify workflow engine options

- src/quacc/recipes/dftb/core.py
- src/quacc/recipes/emt/core.py
- src/quacc/recipes/emt/jobflow/slabs.py
- src/quacc/recipes/emt/parsl/slabs.py
- src/quacc/recipes/emt/prefect/slabs.py
- src/quacc/recipes/emt/slabs.py
- src/quacc/recipes/gaussian/core.py
- src/quacc/recipes/gulp/core.py
- src/quacc/recipes/lj/core.py
- src/quacc/recipes/orca/core.py
- src/quacc/recipes/psi4/core.py
- src/quacc/recipes/tblite/core.py
- src/quacc/recipes/vasp/core.py
- src/quacc/recipes/vasp/mp.py
- src/quacc/recipes/vasp/qmof.py
- src/quacc/recipes/vasp/slabs.py
- src/quacc/schemas/atoms.py
- src/quacc/util/atoms.py
> Refactor atoms parsing

- CHANGELOG.md
- src/quacc/recipes/emt/core.py
- src/quacc/recipes/gulp/core.py
- src/quacc/recipes/vasp/core.py
- src/quacc/recipes/vasp/qmof.py
- tests/recipes/emt/test_emt_recipes.py
- tests/recipes/gulp/test_gulp_recipes.py
- tests/recipes/vasp/test_vasp_recipes.py
> Standardize `relax_cell` to be `False` by default for all recipes

- .github/dependabot.yml
- .github/workflows/docs.yaml
- .github/workflows/mega-linter.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- docs/install/config_db.md
- docs/start/demo.md
- docs/user/atomate2.md
- docs/user/basics.md
- docs/user/database.md
- docs/user/executors.md
- docs/user/wflow_engines.md
- pyproject.toml
- tests/recipes/compiled/test_real_gulp_recipes.py
Addressed some comments in https://scientific-python.github.io/repo-review/?repo=Quantum-Accelerators%2Fquacc&branch=main
> Address scientific-python GitHub repo review comments

- .github/workflows/tests.yaml
- src/quacc/recipes/newtonnet/core.py
- src/quacc/recipes/vasp/core.py
- src/quacc/util/wflows.py
> Add a method to strip decorators

- src/quacc/recipes/orca/core.py
- tests/covalent_tests/test_covalent.py
- tests/recipes/orca/test_orca_recipes.py
> Fix ORCA automatic detection of `mpirun` in PATH

- .gitignore
- Added virtual environments path in `.gitignore`
- Closes: #816
> Updated `.gitignore`

- src/quacc/calculators/qchem.py
- src/quacc/calculators/vasp.py
- src/quacc/utils/calc.py
- src/quacc/utils/files.py
- According to `ruff` updated the code
- #783
> Updated `os.path.abspath()` to `Path.resolve()`

- src/quacc/schemas/ase.py
- src/quacc/schemas/vasp.py
- Replaced the `os.getcwd()` with `Path.cwd()`
- Changes done only scoped to `ruff` errors
- Refs: #783
> Replaced `os.getcwd()`

- src/quacc/recipes/dftb/core.py
- src/quacc/recipes/emt/core.py
- src/quacc/recipes/emt/defects.py
- src/quacc/recipes/gaussian/core.py
- src/quacc/recipes/gulp/core.py
- src/quacc/recipes/lj/core.py
- src/quacc/recipes/newtonnet/core.py
- src/quacc/recipes/newtonnet/ts.py
- src/quacc/recipes/orca/core.py
- src/quacc/recipes/psi4/core.py
- src/quacc/recipes/qchem/core.py
- src/quacc/recipes/qchem/ts.py
- src/quacc/recipes/tblite/core.py
- src/quacc/recipes/vasp/core.py
- src/quacc/recipes/vasp/slabs.py
- src/quacc/utils/defects.py
> Add more docstrings for recipes

- src/quacc/calculators/vasp.py
- src/quacc/recipes/newtonnet/core.py
- src/quacc/recipes/vasp/mp.py
- src/quacc/recipes/vasp/slabs.py
- src/quacc/utils/wflows.py
> Address some `mypy` errors

- README.md
- docs/about/faq.md
- docs/install/codes.md
- docs/install/install.md
- docs/start/demo.md
- docs/user/advanced/database.md
- docs/user/recipes/recipes_intro.md
- docs/user/recipes/recipes_list.md
- docs/user/wflow_engine/wflow_engines1.md
- mkdocs.yml
- src/quacc/calculators/vasp.py
- src/quacc/recipes/dftb/core.py
- src/quacc/recipes/emt/core.py
- src/quacc/recipes/emt/defects.py
- src/quacc/recipes/emt/slabs.py
- src/quacc/recipes/gaussian/core.py
- src/quacc/recipes/gulp/core.py
- src/quacc/recipes/lj/core.py
- src/quacc/recipes/newtonnet/core.py
- src/quacc/recipes/newtonnet/ts.py
- src/quacc/recipes/orca/core.py
- src/quacc/recipes/psi4/core.py
- src/quacc/recipes/qchem/core.py
- src/quacc/recipes/qchem/ts.py
- src/quacc/recipes/tblite/core.py
- src/quacc/recipes/vasp/core.py
- src/quacc/recipes/vasp/mp.py
- src/quacc/recipes/vasp/slabs.py
> Improve hyperlinking in docs

- src/quacc/recipes/lj/core.py
- src/quacc/recipes/newtonnet/core.py
- src/quacc/recipes/newtonnet/ts.py
- src/quacc/recipes/tblite/core.py
- src/quacc/schemas/ase.py
> Refactor `FreqSchema`

- src/quacc/recipes/newtonnet/core.py
> Clean up NewtonNet recipes

- CHANGELOG.md
- tests/utils/test_sella.py
> Add more rigorous tests for use_TRICs

- tests/utils/test_sella.py
> Add more TRICs tests

- src/quacc/custodian/qchem.py
- src/quacc/recipes/qchem/core.py
- src/quacc/settings.py
> Allow for setting of NBO path in Q-Chem settings

- src/quacc/calculators/qchem.py
- tests/calculators/qchem/test_qchem.py
- tests/recipes/qchem/qchem_examples/custodian.json
- tests/recipes/qchem/test_qchem_recipes.py
> Update schema in Q-Chem calculator

- src/quacc/settings.py
> Change default scratch location to CWD

- pyproject.toml
> Revert pmg update

- docs/user/wflow_engine/executors1.md
- docs/user/wflow_engine/executors2.md
- docs/user/wflow_engine/wflow_engines2.md
> Update Parsl docs

- src/quacc/recipes/dftb/core.py
> Refactor DFTB+ error handling

- src/quacc/recipes/orca/core.py
- tests/requirements.txt
> Remove ASE commit pin in test suite

- src/quacc/recipes/emt/defects.py
- src/quacc/recipes/emt/slabs.py
- src/quacc/recipes/vasp/slabs.py
TODO:
- Test that this works "in prod" for Parsl and Covalent
> Simplify subflows

- tests/core/recipes/compiled_recipes/test_real_orca_recipes.py
> Check if Orca size is more then 1 mb

- src/quacc/recipes/common/phonons.py
- src/quacc/recipes/emt/phonons.py
> Use 0.01 for atom displacement default in phonon calcs

- src/quacc/runners/ase.py
- tests/local/recipes/qchem_recipes/test_qchem_recipes.py
> Remove redundant error logging

- src/quacc/calculators/qchem/io.py
- src/quacc/calculators/qchem/qchem.py
> Make units on Q-Chem Hessian ASE-compatible

- src/quacc/settings.py
- tests/covalent/conftest.py
- tests/jobflow/conftest.py
- tests/local/atoms/test_atoms_core.py
- tests/local/atoms/test_slabs.py
- tests/local/calculators/qchem/test_qchem.py
- tests/local/calculators/vasp/test_vasp.py
- tests/local/conftest.py
- tests/local/recipes/gaussian_recipes/conftest.py
- tests/local/recipes/gulp_recipes/conftest.py
- tests/local/recipes/orca_recipes/conftest.py
- tests/local/recipes/qchem_recipes/test_qchem_recipes.py
- tests/local/schemas/test_ase.py
- tests/local/schemas/test_atoms.py
- tests/local/schemas/test_cclib_schema.py
- tests/local/schemas/test_prep.py
- tests/local/schemas/test_vasp_schema.py
- tests/local/settings/test_settings.py
- tests/parsl/conftest.py
- tests/prefect/conftest.py
- tests/redun/conftest.py
> Fix initial import speed

- docs/user/settings/settings.md
Closes #1273, admittedly without a satisfying alternative.
> Remove discussion about in-memory setting swaps

- .github/ISSUE_TEMPLATE/bug.yaml
- docs/user/settings/settings.md
- src/quacc/_cli/quacc.py
> Clean up issue reporting guideline

- docs/user/basics/wflow_syntax.md
- docs/user/wflow_engine/wflow_engines1.md
- docs/user/wflow_engine/wflow_engines2.md
- src/quacc/runners/ase.py
- src/quacc/wflow_tools/decorators.py
- tests/dask/test_dask_tutorials.py
- tests/parsl/test_parsl_tutorials.py
> Clarify dask documentation

- CHANGELOG.md
- src/quacc/atoms/slabs.py
- src/quacc/calculators/espresso/espresso.py
- src/quacc/calculators/qchem/params.py
- src/quacc/recipes/_qchem_legacy/_base.py
- src/quacc/recipes/_qchem_legacy/ts.py
- src/quacc/recipes/dftb/_base.py
- src/quacc/recipes/emt/core.py
- src/quacc/recipes/emt/defects.py
- src/quacc/recipes/gaussian/_base.py
- src/quacc/recipes/gulp/_base.py
- src/quacc/recipes/lj/core.py
- src/quacc/recipes/mlp/core.py
- src/quacc/recipes/newtonnet/core.py
- src/quacc/recipes/newtonnet/ts.py
- src/quacc/recipes/orca/_base.py
- src/quacc/recipes/psi4/_base.py
- src/quacc/recipes/qchem/_base.py
- src/quacc/recipes/qchem/core.py
- src/quacc/recipes/qchem/ts.py
- src/quacc/recipes/tblite/core.py
- src/quacc/recipes/vasp/_base.py
- src/quacc/recipes/vasp/qmof.py
- src/quacc/runners/ase.py
- src/quacc/schemas/ase.py
- src/quacc/schemas/phonons.py
- src/quacc/utils/dicts.py
- src/quacc/utils/files.py
- tests/core/utils/test_dicts.py
> Streamline dict handling function names

- src/quacc/utils/files.py
- tests/core/recipes/espresso_recipes/test_espresso.py
- tests/core/utils/test_files.py
> Fix `copy_decompress_files_from_dir` in CWD

- src/quacc/recipes/mlp/core.py
- src/quacc/utils/files.py
- tests/core/recipes/mlp_recipes/test_core_recipes.py
> Fix `default_dtype` in MACE recipes

- docs/user/recipes/workflows.md
- src/quacc/recipes/emt/defects.py
- src/quacc/recipes/emt/phonons.py
- src/quacc/recipes/emt/slabs.py
- src/quacc/recipes/tblite/phonons.py
- src/quacc/recipes/vasp/mp.py
- src/quacc/recipes/vasp/slabs.py
- src/quacc/wflow_tools/customizers.py
- tests/core/recipes/emt_recipes/test_emt_defect_recipes.py
- tests/core/recipes/emt_recipes/test_emt_recipes.py
- tests/core/recipes/tblite_recipes/test_tblite_phonons.py
- tests/core/recipes/vasp_recipes/mocked/test_vasp_recipes.py
- tests/core/wflow/test_customizers.py
- tests/covalent/test_covalent_recipes.py
- tests/covalent/test_customizers.py
- tests/dask/test_dask_recipes.py
- tests/parsl/test_parsl_recipes.py
- tests/redun/test_redun_recipes.py
Plus a refactoring of `customize_funcs` to not rely on the ordering of keys in a dict.
> `job_parameters` --> `job_params`

- src/quacc/utils/dicts.py
- src/quacc/wflow_tools/customizers.py
> Trivial cleanup

- src/quacc/wflow_tools/customizers.py
- src/quacc/wflow_tools/decorators.py
- tests/dask/test_dask_syntax.py
\>> Provide a description of your changes here, linking to any associated issue reports. <<
> More robust `update_parameters` function

- src/quacc/_cli/quacc.py
- src/quacc/calculators/espresso/__init__.py
- src/quacc/recipes/gulp/core.py
- src/quacc/recipes/orca/core.py
- src/quacc/utils/lists.py
- src/quacc/wflow_tools/decorators.py
> `ruff . --fix`

- src/quacc/recipes/espresso/phonons.py
> Espresso: user should be able to run the flow without sending job_params

- docs/user/basics/wflow_overview.md
- src/quacc/calculators/espresso/espresso.py
- src/quacc/settings.py
As of now there is no way to change binary location neither using .quacc.yaml or the CLI? (Can't change the dictionary directly)
This additional keyword would allow it. If there is already a way then these changes are obsolete but this PR could then be used to explain it better in the doc
> Proposal: improve espresso settings in quacc.yaml

- docs/user/basics/wflow_overview.md
- src/quacc/calculators/espresso/espresso.py
- src/quacc/recipes/espresso/core.py
- tests/core/recipes/espresso_recipes/test_core.py
This should also improve the missing coverage from #1404
> Add test_run parameter to the pw jobs + test

- src/quacc/calculators/qchem/qchem.py
- src/quacc/calculators/vasp/vasp.py
> Use `sys.executable` in subprocesses

- src/quacc/utils/kpts.py
- tests/core/calculators/vasp/test_vasp.py
> Ensure kpts are returned as `int`

- src/quacc/recipes/_qchem_legacy/core.py
- src/quacc/recipes/_qchem_legacy/ts.py
- src/quacc/runners/ase.py
- tests/core/runners/test_sella.py
Removing TRICs support until it is solved upstream: https://github.com/zadorlab/sella/issues/32
> Remove TRICs support until solved upstream

- src/quacc/calculators/espresso/espresso.py
> Reflect new ASE master changes after tests fix

- src/quacc/calculators/espresso/espresso.py
I am pretty sure there is no need to write the input twice 🙃
> Espresso: trivial code duplication

- CHANGELOG.md
- src/quacc/atoms/core.py
- src/quacc/atoms/phonons.py
- src/quacc/recipes/common/phonons.py
- src/quacc/recipes/emt/phonons.py
- src/quacc/recipes/tblite/phonons.py
- tests/core/atoms/test_phonons.py
- tests/core/recipes/emt_recipes/test_emt_phonons.py
- tests/core/recipes/tblite_recipes/test_tblite_phonons.py
> Make common phonon flow more efficient

- .github/workflows/tests.yaml
- CHANGELOG.md
- docs/user/recipes/recipes_list.md
- src/quacc/recipes/mlp/_base.py
- src/quacc/recipes/mlp/core.py
- src/quacc/recipes/mlp/phonons.py
- tests/core/recipes/mlp_recipes/test_core_recipes.py
- tests/core/recipes/mlp_recipes/test_phonon_recipes.py
```python
from quacc.recipes.mlp.phonons import phonon_flow
from ase.io import read
atoms = read("structure.cif")
output = phonon_flow(atoms, method="mace")
print(output)
```
> Add MLP phonon workflow

- src/quacc/atoms/core.py
- src/quacc/schemas/atoms.py
- tests/core/recipes/lj_recipes/test_lj_recipes.py
Closes #1645 (and hopefully doesn't break anything?).
> Safer handling of charge and spin metadata

- pyproject.toml
- tests/requirements-covalent.txt
Requires:
- https://github.com/AgnostiqHQ/covalent/pull/1916
> Update covalent dependencies

- pyproject.toml
- tests/core/recipes/mlp_recipes/test_core_recipes.py
- tests/requirements-mlp.txt
> bump `matgl`

- CHANGELOG.md
- src/quacc/_cli/quacc.py
- tests/core/cli/test_cli.py
> Add a validity checker on CLI parameters

- src/quacc/schemas/ase.py
- src/quacc/schemas/vasp.py
- tests/core/schemas/test_ase.py
- tests/core/schemas/test_vasp_schema.py
> Fix and add tests for `dir_name`

- pyproject.toml
- tests/requirements.txt
> Bump pymatgen

- pyproject.toml
- src/quacc/calculators/vasp/vasp.py
- src/quacc/calculators/vasp/vasp_custodian.py
- tests/core/calculators/vasp/test_vasp.py
- tests/core/recipes/vasp_recipes/mocked/conftest.py
- tests/requirements.txt
> Refactor subprocess calls in VASP

- src/quacc/calculators/qchem/qchem.py
- src/quacc/calculators/qchem/qchem_custodian.py
- tests/core/recipes/qchem_recipes/mocked/test_qchem_recipes.py
> Refactor subprocess calls for Q-Chem

- tests/core/recipes/vasp_recipes/mocked/test_vasp_recipes.py
> Add more MP VASP tests

- CHANGELOG.md
- src/quacc/recipes/vasp/mp.py
- tests/core/recipes/vasp_recipes/mocked/test_vasp_recipes.py
- tests/core/schemas/test_vasp_schema.py
Fixes an important issue with the double-relaxes by ensuring we don't do the same relaxation twice.
> Fix MP double-relax

- pyproject.toml
- src/quacc/utils/files.py
- tests/core/runners/test_prep.py
- tests/core/utils/test_files.py
- tests/requirements.txt
Continuation of #1759.
Requires: https://github.com/materialsvirtuallab/monty/pull/628
> Improve `copy_files` handling: Part 2/3

- tests/requirements.txt
Reverts Quantum-Accelerators/quacc#1812
> Revert "Bump pymatgen from 2024.2.23 to 2024.3.1"

- tests/requirements-defects.txt
- tests/requirements.txt
> Bump pymatgen and shakenbreak

- src/quacc/recipes/common/phonons.py
- src/quacc/runners/phonons.py
- src/quacc/runners/prep.py
- src/quacc/schemas/phonons.py
- tests/core/recipes/emt_recipes/test_emt_phonons.py
> Refactor phonopy schema

- docs/user/advanced/vasp_hpc.md
- docs/user/wflow_engine/executors1.md
- docs/user/wflow_engine/executors2.md
- docs/user/wflow_engine/wflow_engines1.md
- pyproject.toml
- tests/requirements-covalent.txt
> Update Covalent docs

- src/quacc/calculators/vasp/vasp.py
- src/quacc/calculators/vasp/vasp_custodian.py
I'm reverting this change for now until we sort out https://github.com/materialsproject/custodian/issues/316 upstream.
> Revert custodian subprocess in VASP

- .github/workflows/tests.yaml
> Fix psi4 test suite

- src/quacc/wflow_tools/customizers.py
- tests/core/wflow/test_customizers.py
- tests/covalent/test_emt_recipes.py
- tests/dask/test_emt_recipes.py
- tests/parsl/test_emt_recipes.py
- tests/prefect/test_emt_recipes.py
- tests/redun/test_emt_recipes.py
> Add more customize_funcs tests

- src/quacc/schemas/ase.py
- src/quacc/schemas/cclib.py
- src/quacc/schemas/phonons.py
- src/quacc/schemas/vasp.py
- tests/core/recipes/emt_recipes/test_emt_recipes.py
- tests/core/recipes/lj_recipes/test_lj_recipes.py
- tests/core/schemas/test_ase.py
> gzip the pickle files if `GZIP_FILES` is True

- src/quacc/utils/files.py
- tests/core/utils/test_files.py
Attempt to fix https://github.com/Quantum-Accelerators/quacc/issues/1933
> Small changes in copy_decompress_files

- src/quacc/recipes/espresso/dos.py
This is just personal preference and none of it influences the execution.
> Trivial Espresso DOS cleanup

- src/quacc/calculators/espresso/espresso.py
- src/quacc/calculators/espresso/utils.py
- src/quacc/recipes/espresso/_base.py
- src/quacc/recipes/espresso/core.py
- src/quacc/recipes/espresso/phonons.py
> Apply `ruff` "D" fixes

- src/quacc/_cli/quacc.py
- src/quacc/atoms/defects.py
- src/quacc/atoms/slabs.py
- src/quacc/settings.py
> Apply ruff `N` rules

- pyproject.toml
- src/quacc/_cli/quacc.py
- src/quacc/atoms/defects.py
- src/quacc/settings.py
- tests/core/schemas/test_cclib_schema.py
> Add more ruff rules

- pyproject.toml
- src/quacc/_cli/quacc.py
- src/quacc/utils/files.py
- tests/requirements.txt
> Remove calls to pyyaml and upgrade pymatgen

- src/quacc/runners/thermo.py
Get just the point group data in the thermo function.
> More efficient thermo function

- src/quacc/schemas/ase.py
- src/quacc/schemas/atoms.py
- src/quacc/schemas/cclib.py
- src/quacc/schemas/phonons.py
- src/quacc/schemas/vasp.py
- src/quacc/settings.py
- src/quacc/utils/dicts.py
Internal refactoring of schemas to prevent code duplication.
> Clean up schemas

- src/quacc/runners/thermo.py
> Remove unnecessary PBC check

- src/quacc/recipes/emt/core.py
- src/quacc/recipes/espresso/_base.py
- src/quacc/recipes/espresso/core.py
- src/quacc/recipes/lj/core.py
- src/quacc/recipes/mlp/core.py
- src/quacc/recipes/newtonnet/core.py
- src/quacc/recipes/newtonnet/ts.py
- src/quacc/recipes/onetep/_base.py
- src/quacc/recipes/onetep/core.py
- src/quacc/recipes/orca/_base.py
- src/quacc/recipes/orca/core.py
- src/quacc/recipes/qchem/_base.py
- src/quacc/recipes/qchem/core.py
- src/quacc/recipes/qchem/ts.py
- src/quacc/recipes/tblite/core.py
- src/quacc/recipes/vasp/_base.py
- src/quacc/recipes/vasp/core.py
- src/quacc/runners/ase.py
Some improvements to type hints.
> Clearer type hint for `opt_params`

- src/quacc/calculators/espresso/espresso.py
Ask says to instantiate a `GenericFileIOCalculator` directly in such scenarios rather than inherit from the base class. Indeed, it seems like this is a slightly more compact way to go.
> Cleanup of Espresso class

- src/quacc/calculators/espresso/espresso.py
> Fix `parallel_info` in Espresso calculator

- pyproject.toml
- tests/covalent/test_emt_recipes.py
- tests/requirements-covalent.txt
> Update Covalent 

- pyproject.toml
> Update pyproject.toml to have a more specific ASE version

- src/quacc/recipes/vasp/qmof.py
- tests/core/recipes/vasp_recipes/mocked/test_vasp_recipes.py
> Remove warning from QMOF recipe

- src/quacc/recipes/vasp/qmof.py
The context handler does not need to be around the whole function.
> Slight cleanup of QMOF recipe

- src/quacc/recipes/espresso/dos.py
- src/quacc/recipes/espresso/phonons.py
Just some minor refactoring of the internal guts of espresso recipes, making `customize_funcs()` a bit cleaner.
> Clean up of Espresso flow internals

- pyproject.toml
- tests/requirements-sella.txt
> Bump sella

- src/quacc/schemas/phonons.py
\>> Describe your changes here. Make sure to reference any associated issues. <<
> Update phonopy requires

- src/quacc/atoms/defects.py
- src/quacc/atoms/phonons.py
- src/quacc/calculators/qchem/qchem_custodian.py
- src/quacc/calculators/vasp/params.py
- src/quacc/recipes/common/defects.py
- src/quacc/recipes/common/phonons.py
- src/quacc/recipes/emt/defects.py
- src/quacc/recipes/mlp/phonons.py
- src/quacc/recipes/newtonnet/core.py
- src/quacc/recipes/newtonnet/ts.py
- src/quacc/recipes/psi4/core.py
- src/quacc/recipes/qchem/core.py
- src/quacc/recipes/qchem/ts.py
- src/quacc/recipes/tblite/core.py
- src/quacc/recipes/tblite/phonons.py
- src/quacc/recipes/vasp/mp.py
- src/quacc/runners/ase.py
- src/quacc/runners/phonons.py
- src/quacc/schemas/phonons.py
- tests/core/calculators/qchem/test_qchem.py
- tests/core/recipes/mlp_recipes/test_core_recipes.py
- tests/core/recipes/qchem_recipes/mocked/test_qchem_recipes.py
- tests/dask/conftest.py
- tests/parsl/conftest.py
- tests/prefect/conftest.py
Minor refactoring of import checking.
> Clean up import checks

- src/quacc/recipes/newtonnet/ts.py
Removes a duplicate calculator instantiation.
> Minor cleanup of newtonnet TS recipe

- src/quacc/calculators/vasp/params.py
- tests/core/calculators/vasp/test_vasp.py
1. Report which settings were actually changed.
2. Remove extraneous "Copilot:" from log.
> Improve VASP logging

- src/quacc/atoms/core.py
> Fix MD5 hash for FIPS encryption compatability

- src/quacc/settings.py
Minor refactoring of settings modulee.
> Slight refactoring of settings

- tests/covalent/test_customizers.py
- tests/dask/test_customizers.py
- tests/prefect/test_customizers.py
- tests/redun/test_customizers.py
> Further support for double application of `settings_swap`

- docs/about/contributors.md
This PR updates the `contributors.md`, adding a brief contribution I did (#2163). 
- Your PR should be focused on a [single feature addition or bugfix](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/best-practices-for-pull-requests#write-small-prs).
- Your PR should have relevant, comprehensive [unit tests](https://quantum-accelerators.github.io/quacc/dev/contributing.html#unit-tests).
- Your PR should be on a custom branch and _not_ be named `main`.
- If you are an external contributor, you will see a comment from [@buildbot-princeton](https://github.com/buildbot-princeton). This is solely for …
> updating contributors.md

- pyproject.toml
- tests/core/calculators/qchem/test_qchem.py
- tests/core/calculators/vasp/test_vasp.py
- tests/core/recipes/dftb_recipes/test_dftb_recipes.py
- tests/core/recipes/mlp_recipes/test_core_recipes.py
- tests/core/recipes/qchem_recipes/mocked/test_qchem_recipes.py
- tests/core/runners/test_ase.py
- tests/core/runners/test_prep.py
- tests/core/schemas/test_ase.py
- tests/core/schemas/test_cclib_schema.py
- tests/core/schemas/test_vasp_pop_analysis.py
- tests/core/wflow/test_customizers.py
- tests/covalent/test_customizers.py
fix: https://github.com/Quantum-Accelerators/quacc/issues/1708
> tests: improve error handling

- src/quacc/runners/ase.py
> zpath(Path) -> zpath(str(Path))

- src/quacc/recipes/espresso/phonons.py
Specifies keyword arguments in `grid_phonon_flow` that were provided as positional arguments.
> Specify keyword arguments explicitly

- tests/requirements.txt
> Remove matplotlib from tests/requirements.txt

- src/quacc/calculators/vasp/params.py
- src/quacc/recipes/orca/core.py
- src/quacc/settings.py
- tests/core/calculators/vasp/test_vasp.py
- tests/prefect/test_syntax.py
Automatically set NCORE to sqrt(# of cores) unless otherwise specified by the user.
> Better NCORE handling

- docs/user/recipes/recipes_list.md
- src/quacc/recipes/mlp/core.py
- src/quacc/recipes/mlp/phonons.py
Minor updates to the static/relax MLP jobs and docs to allow fairchem calculators.
> minor updates to docs to include fairchem mlp options

- src/quacc/recipes/mlp/phonons.py
\>> Provide context and a description of your changes here. Make sure to reference any associated issues. <<
> include tensornet as method in phonons.py

- src/quacc/calculators/vasp/presets/BulkSet.yaml
- src/quacc/calculators/vasp/presets/RosenFastSetPBE.yaml
- src/quacc/calculators/vasp/presets/RosenFastSetR2SCAN
- tests/core/calculators/vasp/test_vasp.py
- tests/core/recipes/emt_recipes/test_emt_defect_recipes.py
- tests/core/recipes/mlp_recipes/test_core_recipes.py
Some minor CI cleanup to ensure tests run on local machines to completion. Does not impact utility.
> CI cleanup

- tests/core/recipes/vasp_recipes/mocked/test_vasp_recipes.py
> Re-enable tests on Windows
